namespace Wuest.FlatFileParser.Definition
{
	/// <summary>
	/// This enum contains the error codes generated by this library.
	/// These are intended to provide insight into why an error occurred.
	/// It is up to those using the library how to present these errors to the user.
	/// </summary>
	public enum ErrorCodes : short
	{
		/// <summary>
		/// No error has occurred, everything processed successfully.
		/// </summary>
		NoError = 0
	}
}
